# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - master
  - feature/*

stages:
- stage: BuildApplication
  jobs:
  - job: buildJob
    timeoutInMinutes: 10
    pool:
      name: MyPool
      demands: 
      - dotnet
      - nunit-console
    variables:
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Debug'
    steps:
    - task: DotNetCoreCLI@0
      inputs:
        command: build
        projects: SaverBackend/SaverBackend.csproj
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/s'
        artifact: 'BuildArtifacts'
        publishLocation: 'pipeline'

- stage: DeployApplication
  dependsOn: BuildApplication
  jobs:
  - deployment: deploy
    displayName: 'Deploy code to raspberry pi'
    pool:
      name: MyPool
      demands: dotnet
    workspace:
      clean: all
    environment:
      name: raspberry
    strategy:
      runOnce:
        deploy:
          steps:
            - bash: 'sudo service redis-server start'
            - bash: 'cd /home/pi/azureagent/_work/1/BuildArtifacts/SaverBackend/bin/Debug/net6.0/'
            - bash: 'sudo nohup dotnet /home/pi/azureagent/_work/1/BuildArtifacts/SaverBackend/bin/Debug/net6.0/SaverBackend.dll -d --urls=http://0.0.0.0:5000/ --configuration debug > /dev/null 2>&1 &'