# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master
  - feature/*

stages:
- stage: BuildApplication
  jobs:
  - job: buildJob
    timeoutInMinutes: 10
    pool:
      name: MyPool
      demands: 
      - dotnet
    variables:
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Debug'
    steps:
    - task: DotNetCoreCLI@0
      inputs:
        command: build
        projects: LiveHost/LiveHost.csproj
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/s'
        artifact: 'BuildDrop'
        publishLocation: 'pipeline'
