// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML.Data;

namespace ImageRecognitionNN
{
    public partial class ImageLearning
    {
        /// <summary>
        /// model input class for ImageLearning.
        /// </summary>
        public class ModelInput
        {
            [ColumnName(@"Label")]
            public string Label { get; set; }

            [ColumnName(@"ImageSource")]
            public byte[] ImageSource { get; set; }

        }
    }
}
