// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaverBackend.Models;

#nullable disable

namespace SaverBackend.Db.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260918122524_AddNewColumns")]
    partial class AddNewColumns
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SaverBackend.Models.BrokenContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ImageUri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("BrokenContents");
                });

            modelBuilder.Entity("SaverBackend.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AmountOfFavorites")
                        .HasColumnType("int");

                    b.Property<int?>("AmountOfOpenings")
                        .HasColumnType("int");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<int?>("ProfileId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("ProfileId");

                    b.HasIndex("ProfileId1");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("SaverBackend.Models.Content", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImageUri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAiGenerated")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("int");

                    b.Property<short>("Rating")
                        .HasColumnType("smallint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("Contents");
                });

            modelBuilder.Entity("SaverBackend.Models.ContentProfile", b =>
                {
                    b.Property<int>("FavoriteContentId")
                        .HasColumnType("int");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.HasKey("FavoriteContentId", "ProfileId");

                    b.HasIndex("ProfileId");

                    b.ToTable("contentprofile");
                });

            modelBuilder.Entity("SaverBackend.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("SaverBackend.Models.ImageModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("SaverBackend.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Funds")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("ProfileId1")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VerificationCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId1");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("SaverBackend.Models.VideoContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VideoUri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("SaverBackend.Models.Category", b =>
                {
                    b.HasOne("SaverBackend.Models.Group", null)
                        .WithMany("GrouppedCategories")
                        .HasForeignKey("GroupId");

                    b.HasOne("SaverBackend.Models.Profile", "Profile")
                        .WithMany("PublishedCategories")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaverBackend.Models.Profile", null)
                        .WithMany("FavoriteCategories")
                        .HasForeignKey("ProfileId1");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("SaverBackend.Models.Content", b =>
                {
                    b.HasOne("SaverBackend.Models.Profile", null)
                        .WithMany("Publications")
                        .HasForeignKey("ProfileId");
                });

            modelBuilder.Entity("SaverBackend.Models.ContentProfile", b =>
                {
                    b.HasOne("SaverBackend.Models.Content", null)
                        .WithMany()
                        .HasForeignKey("FavoriteContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaverBackend.Models.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SaverBackend.Models.Group", b =>
                {
                    b.HasOne("SaverBackend.Models.Profile", null)
                        .WithMany("Groups")
                        .HasForeignKey("ProfileId");
                });

            modelBuilder.Entity("SaverBackend.Models.Profile", b =>
                {
                    b.HasOne("SaverBackend.Models.Profile", null)
                        .WithMany("Friends")
                        .HasForeignKey("ProfileId1");
                });

            modelBuilder.Entity("SaverBackend.Models.VideoContent", b =>
                {
                    b.HasOne("SaverBackend.Models.Profile", "Profile")
                        .WithMany("VideoContents")
                        .HasForeignKey("ProfileId");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("SaverBackend.Models.Group", b =>
                {
                    b.Navigation("GrouppedCategories");
                });

            modelBuilder.Entity("SaverBackend.Models.Profile", b =>
                {
                    b.Navigation("FavoriteCategories");

                    b.Navigation("Friends");

                    b.Navigation("Groups");

                    b.Navigation("Publications");

                    b.Navigation("PublishedCategories");

                    b.Navigation("VideoContents");
                });
#pragma warning restore 612, 618
        }
    }
}
